service: cashbotic

provider:
  name: aws
  runtime: python3.12  
  region: ap-southeast-2
  memorySize: 256       
  timeout: 20           
  environment:
    TOKEN: ${env:TOKEN}
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
    GOOGLE_TOKEN_B64: ${env:GOOGLE_TOKEN_B64}

functions:
  webhook:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: webhook
          method: any    

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux  

outputs:
  apiGatewayUrl:
    value: https://${aws:restApiId}.execute-api.${aws:region}.amazonaws.com/${sls:stage}
