name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH

    - name: Deploy to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: flyctl deploy --config fly.toml --remote-only

    - name: Wait for Fly App to be live
      run: |
        echo "Waiting for app to become reachable..."
        until curl --silent --fail https://cashbotic-123.fly.dev/; do
            sleep 3
        done

    - name: Set Telegram Webhook
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        curl -X POST "https://api.telegram.org/bot${TOKEN}/setWebhook" \
             -d "url=https://cashbotic-123.fly.dev/webhook"
